import { writeTextAtomic } from "../atomic-file.js";
import { auditFactoryTraveler } from "./traveler.js";

const EVIDENCE_REF = /^sha256:[a-f0-9]{64}$/;

export function writeFactoryReport(filePath, events, options = {}) {
  return writeTextAtomic(filePath, renderFactoryReport(events, options));
}

export function collectFactoryReportEvidence(store, events, { limit = 10_000 } = {}) {
  if (!store || typeof store.getEvidence !== "function") throw new TypeError("factory report evidence requires a factory store");
  const queue = [...referencesIn(events)];
  const evidence = {};
  while (queue.length && Object.keys(evidence).length < limit) {
    const reference = queue.shift();
    if (Object.hasOwn(evidence, reference)) continue;
    try {
      const value = store.getEvidence(reference);
      evidence[reference] = value;
      for (const nested of referencesIn(value)) if (!Object.hasOwn(evidence, nested)) queue.push(nested);
    } catch {
      // Some hashes identify events, routes, or external artifacts rather than blobs.
    }
  }
  return evidence;
}

export function renderFactoryReport(events, {
  sequence = events.length,
  title = "BANTAMFACTORY — CHICKEN FLOOR",
  evidence = {},
  workforce = null,
  liveEndpoint = null,
  blueprintEndpoint = null,
  pollIntervalMs = 1_000,
} = {}) {
  const audit = auditFactoryTraveler(events);
  if (!Number.isInteger(sequence) || sequence < 1 || sequence > events.length) {
    throw new Error(`factory report sequence must be between 1 and ${events.length}`);
  }
  if (liveEndpoint !== null && (typeof liveEndpoint !== "string" || !liveEndpoint.startsWith("/") || liveEndpoint.startsWith("//"))) {
    throw new Error("factory report live endpoint must be a same-origin absolute path");
  }
  if (blueprintEndpoint !== null && (typeof blueprintEndpoint !== "string" || !blueprintEndpoint.startsWith("/") || blueprintEndpoint.startsWith("//"))) {
    throw new Error("factory blueprint endpoint must be a same-origin absolute path");
  }
  if (!Number.isInteger(pollIntervalMs) || pollIntervalMs < 100 || pollIntervalMs > 60_000) {
    throw new Error("factory report poll interval must be between 100 and 60000ms");
  }
  const data = safeScriptJson({ schema: 3, kind: "bantam.factory-report-data", sequence, audit, events, evidence, workforce, liveEndpoint, pollIntervalMs });
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)}</title>
<style>
:root{color-scheme:dark;--ink:#f4e5bd;--cream:#d8c79d;--muted:#8f8a75;--gold:#e9b94f;--gold2:#8c682d;--green:#8dd66f;--red:#f06b51;--blue:#77a8b5;--panel:#111512;--panel2:#191c17;--edge:#4a4939;--floor:#171916;--machine:#30372c;--shadow:0 18px 45px #000b}
*{box-sizing:border-box}html{background:#090b09}body{margin:0;min-height:100vh;color:var(--ink);font:12px/1.4 ui-monospace,SFMono-Regular,Menlo,monospace;background:radial-gradient(circle at 45% -20%,#3f3824 0,transparent 34%),#0b0d0b}
header{height:68px;position:sticky;top:0;z-index:30;display:flex;align-items:stretch;background:#0b0e0cfa;border-bottom:1px solid #665737;box-shadow:0 10px 30px #000b;backdrop-filter:blur(12px)}
.brand{display:flex;align-items:center;gap:13px;padding:0 24px;border-right:1px solid #34372e}.brand-mark{font-size:29px;filter:drop-shadow(0 3px 4px #000)}h1{margin:0;color:#edcb83;font:800 20px/1 system-ui,sans-serif;letter-spacing:.08em;white-space:nowrap}.job{display:flex;align-items:center;min-width:0;max-width:300px;padding:0 20px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#857f69}
.header-metrics{margin-left:auto;display:flex}.head-metric{min-width:112px;padding:12px 18px;border-left:1px solid #34372e}.head-metric span{display:block;color:#777463;font-size:8px;text-transform:uppercase;letter-spacing:.17em}.head-metric b{display:block;margin-top:4px;color:#e8dbb9;font-size:14px}.blueprint-link{display:flex;align-items:center;margin:11px 0;padding:0 14px;border:1px solid #665737;border-radius:3px;color:#e7bb5b;text-decoration:none;font-weight:900;letter-spacing:.08em}.blueprint-link:hover{background:#302918}.status{display:flex;align-items:center;margin:11px 16px;padding:0 16px;border:1px solid;border-radius:3px;font-weight:900;text-transform:uppercase;letter-spacing:.08em}.ok{color:var(--green)}.bad{color:var(--red)}.wait{color:var(--gold)}.unknown{color:var(--blue)}
main{max-width:1920px;margin:auto;padding:12px;display:grid;gap:10px}.plant-grid{display:grid;grid-template-columns:minmax(760px,1fr) 370px;gap:10px;align-items:start}.panel,.plant-deck{border:1px solid var(--edge);border-radius:5px;background:linear-gradient(160deg,#181b17f7,#0e110ffb);box-shadow:var(--shadow);overflow:hidden}.panel h2,.deck-title{margin:0;padding:9px 13px;border-bottom:1px solid #3a3b31;color:#b8aa82;font:800 9px/1 system-ui,sans-serif;letter-spacing:.16em;text-transform:uppercase}.deck-title{display:flex;justify-content:space-between}.deck-title span:last-child{color:#655f4d}
.floor-shell{position:relative;min-height:470px;overflow:auto;padding:28px 26px 32px;background-color:var(--floor);background-image:linear-gradient(#ffffff05 1px,transparent 1px),linear-gradient(90deg,#ffffff05 1px,transparent 1px),radial-gradient(circle at 50% 50%,#36312155,transparent 46%);background-size:32px 32px,32px 32px,100% 100%}.floor-shell:before{content:"";position:absolute;left:3%;right:3%;top:47%;height:52px;border:3px solid #272a24;border-radius:24px;background:repeating-linear-gradient(90deg,#796338 0 18px,#a98a47 18px 22px,#292b27 22px 44px);box-shadow:inset 0 0 0 6px #151815,0 4px 12px #000a}.floor-shell:after{content:"→  →  →  →  →  →  →  →  →";position:absolute;left:7%;right:7%;top:calc(47% + 16px);overflow:hidden;white-space:nowrap;word-spacing:62px;color:#f2c95d99;font-size:16px;text-shadow:0 0 9px #e9b94f}.floor{position:relative;z-index:2;display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:78px 18px;align-items:start}.floor.ten{grid-template-columns:repeat(5,minmax(135px,1fr))}.floor.ten .station:nth-child(6){grid-row:2;grid-column:5}.floor.ten .station:nth-child(7){grid-row:2;grid-column:4}.floor.ten .station:nth-child(8){grid-row:2;grid-column:3}.floor.ten .station:nth-child(9){grid-row:2;grid-column:2}.floor.ten .station:nth-child(10){grid-row:2;grid-column:1}
.station{position:relative;min-width:0;height:178px;padding:38px 9px 8px;border:1px solid #484b3e;border-bottom:4px solid #252921;border-radius:3px;background:linear-gradient(145deg,#242922f5,#10130ff8);box-shadow:5px 7px 0 #060806aa,0 0 0 1px #080a08;cursor:pointer;transition:.18s ease}.station:hover{transform:translateY(-3px);border-color:#8b7545}.station.selected{transform:translateY(-5px);border-color:var(--gold)!important;box-shadow:0 0 0 2px #e9b94f66,0 0 32px #e9b94f48,5px 9px 0 #080907}.station.running,.station.awaiting-inspection,.station.awaiting-release{border-color:var(--gold)}.station.released{border-color:#4c7042}.station.fail,.station.blocked,.station.infrastructure,.station.contained{border-color:var(--red);box-shadow:0 0 25px #f06b5133,5px 7px #080907}@keyframes pulse{50%{filter:brightness(1.12)}}
.station-head{position:absolute;left:6px;right:6px;top:-10px;height:40px;display:flex;align-items:center;gap:7px;padding:5px 8px;background:#d6c49a;color:#252219;border:2px solid #191c17;box-shadow:0 3px 0 #0008}.station-index{min-width:24px;height:24px;display:grid;place-items:center;background:#35372e;color:#f6d36b;font-weight:900}.station-title{font:800 10px/1.12 system-ui,sans-serif;text-transform:uppercase;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.station-id{display:none}
.machine{height:70px;position:relative;border:2px solid #596052;background:linear-gradient(135deg,#4b5544,#232a22 62%);box-shadow:inset 5px 5px #ffffff0b,inset -5px -5px #0005}.station:nth-child(2n) .machine{background:radial-gradient(circle at 45% 58%,#1a1e19 0 17px,#66705d 18px 21px,transparent 22px),linear-gradient(135deg,#414b3c,#20251f)}.station:nth-child(3n) .machine{background:linear-gradient(90deg,transparent 38%,#151914 39% 62%,transparent 63%),linear-gradient(135deg,#566149,#292f27)}.station:nth-child(5n) .machine{background:radial-gradient(circle at 48% 50%,#bea348 0 4px,#20251e 5px 16px,#697260 17px 21px,transparent 22px),linear-gradient(#485141,#242a23)}.station:nth-child(7n) .machine{background:repeating-linear-gradient(90deg,#3e483a 0 12px,#222820 12px 18px)}.machine:before{content:"";position:absolute;left:10px;right:10px;bottom:9px;height:17px;border:2px solid #768071;background:repeating-linear-gradient(90deg,#171a16 0 13px,#30352d 13px 17px)}.machine:after{content:"";position:absolute;right:10px;top:9px;width:11px;height:11px;border-radius:50%;background:#6d342d;border:3px solid #171b16;box-shadow:0 0 0 2px #5d312a}.station.running .machine:after{background:var(--gold);box-shadow:0 0 11px 4px #e9b94f99}.station.awaiting-inspection .machine:after,.station.awaiting-release .machine:after{background:#ef9a4b;box-shadow:0 0 11px 4px #ef9a4b88;animation:pulse .8s steps(2) infinite}.station.released .machine:after{background:var(--green);box-shadow:0 0 9px 3px #8dd66f77}.station.fail .machine:after,.station.blocked .machine:after,.station.infrastructure .machine:after,.station.contained .machine:after{background:var(--red);box-shadow:0 0 10px 4px #f06b5188}.gauge{position:absolute;left:9px;top:8px;min-width:38px;padding:2px 5px;border:1px solid #24271f;background:#d9dfc7;color:#1b211a;text-align:center;font-size:8px;font-weight:900;text-transform:uppercase}.button-label{position:absolute;right:8px;bottom:10px;color:#e9c873;font-size:7px;letter-spacing:.12em}
.chicken{position:absolute;z-index:4;right:24px;bottom:1px;width:40px;height:40px;filter:drop-shadow(0 4px 3px #0009);transition:.2s}.chicken svg,.worker-icon svg{display:block;width:100%;height:100%}.station.running .chicken{animation:peck .62s ease-in-out infinite}.station.awaiting-inspection .chicken,.station.awaiting-release .chicken{transform:translateX(-30px);opacity:.8}.station.released .chicken{animation:idle 2.2s ease-in-out infinite}@keyframes peck{50%{transform:translate(6px,2px) rotate(8deg)}}@keyframes idle{50%{transform:translateY(-2px)}}body.replay .station *{animation-play-state:paused!important}.rooster{position:absolute;z-index:8;left:8px;bottom:-49px;width:46px;height:46px;filter:drop-shadow(0 4px 4px #000);animation:patrol 1.8s ease-in-out infinite}.rooster svg{width:100%;height:100%;filter:brightness(1.15)}.rooster:after{content:"SUP";position:absolute;left:13px;top:39px;color:#e7b34d;font:900 7px monospace;letter-spacing:.12em}@keyframes patrol{50%{transform:translateX(5px)}}
.wicket{position:absolute;left:7px;right:7px;bottom:-12px;height:9px;border:2px solid #5c6154;border-bottom:0}.released .wicket{border-color:var(--green);box-shadow:0 -4px 9px #8dd66f2a}.blocked .wicket,.fail .wicket,.infrastructure .wicket,.contained .wicket{border-color:var(--red)}.belt-cart{position:absolute;z-index:7;bottom:-45px;left:50%;transform:translateX(-50%);width:62px;height:24px;border:2px solid #2a2115;border-radius:11px;background:linear-gradient(#e8b74d,#8e5f20);box-shadow:0 0 15px #e9b94f77,inset 0 4px #ffe19a}.belt-cart:before{content:"";position:absolute;left:12px;right:12px;top:-7px;height:10px;border-radius:6px;background:#ddad46;border:2px solid #2a2115}.belt-cart:after{content:"";position:absolute;left:7px;right:7px;bottom:-6px;height:7px;background:radial-gradient(circle,#080908 0 3px,transparent 4px) 0 0/23px 7px}.belt-cart span{display:none}
.station-meta{display:grid;grid-template-columns:auto minmax(0,1fr) auto minmax(0,1fr);gap:2px 5px;margin-top:6px;font-size:8px}.station-meta span{color:#777563;text-transform:uppercase}.station-meta b{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#ddd1ae}.station-meta span:nth-child(5),.station-meta b:nth-child(6){grid-column:auto/span 1}.station-meta span:nth-child(9),.station-meta b:nth-child(10){display:none}
.transport{display:grid;grid-template-columns:auto auto minmax(180px,1fr) auto auto auto repeat(2,minmax(80px,auto));align-items:center;gap:7px;padding:9px 11px;border-top:1px solid #4b4431;background:linear-gradient(#161914,#0d100d)}button,select{font:inherit;color:var(--cream);background:#242820;border:1px solid #5b5947;border-radius:3px;padding:6px 9px;cursor:pointer;box-shadow:0 2px #0008}button:hover,button.active,select:hover{border-color:var(--gold);color:#ffe69a}.transport input{width:100%;accent-color:var(--gold)}.live-control{min-width:73px}.live-control.connected{border-color:var(--green);color:var(--green)}.live-control.error{border-color:var(--red);color:var(--red)}.metric{border-left:1px solid #3f4136;padding-left:10px}.metric b{display:block;color:#ece2c6;font-size:11px}.metric span{font-size:7px;color:#777463;text-transform:uppercase;letter-spacing:.1em}.timeline-wrap{min-height:100px;padding:10px 11px;background:repeating-linear-gradient(90deg,transparent 0 49px,#2a2d2522 50px),#0c0f0c;border-top:1px solid #272a24}.timeline{height:76px;display:flex;align-items:center;gap:5px;overflow-x:auto;padding:0 3px}.event{flex:0 0 10px;height:10px;border-radius:50%;background:#6e755f;border:1px solid #111;cursor:pointer;transition:.16s}.event:hover{background:var(--gold);transform:scale(1.45)}.event.current{flex-basis:190px;height:28px;border-radius:3px;display:grid;grid-template-columns:30px 1fr;align-items:center;gap:7px;padding:0 8px;background:#6b5222;border-color:#d8ae4c;color:#fff1b3}.event:not(.current)>*{display:none}.event.current time{display:none}.event.current .seq{color:#d6b760}.event.current b{overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.event.current .detail{display:none}
.inspector{min-height:674px;background:linear-gradient(145deg,#20231d,#0e100e)}.inspect-tabs{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid #3b3b31}.inspect-tabs button{border:0;border-right:1px solid #3b3b31;border-radius:0;box-shadow:none;padding:10px 3px;font-size:8px}.inspect-tabs button.active{background:#d5b05a;color:#211d15}.inspect-body{padding:13px;max-height:610px;overflow:auto}.inspect-body h3{margin:12px 0 7px;color:#e9c36a;font:800 11px system-ui,sans-serif;text-transform:uppercase;letter-spacing:.08em}.chassis-preview{position:relative;height:106px;display:flex;align-items:center;gap:15px;margin-bottom:10px;padding:12px;background:radial-gradient(circle at 30% 45%,#5e4c2866,transparent 37%),linear-gradient(#151913,#0c0f0c);border:1px solid #464638}.chassis-model{position:relative;width:108px;height:39px;border:3px solid #332616;border-radius:17px 22px 13px 18px;background:linear-gradient(145deg,#f2c65d,#8b5a20);box-shadow:inset 0 6px #ffe7a0,0 0 18px #dba64255}.chassis-model:before{content:"";position:absolute;left:25px;right:22px;top:-12px;height:19px;border:3px solid #332616;border-radius:12px 14px 3px 3px;background:#c89134}.chassis-model:after{content:"";position:absolute;left:11px;right:8px;bottom:-8px;height:9px;background:radial-gradient(circle,#090a08 0 5px,transparent 6px) 0 0/48px 10px}.chassis-copy{min-width:0}.chassis-copy b{display:block;color:#e4c371}.chassis-copy small{display:block;margin-top:4px;color:#777463;word-break:break-all}.chassis-pass{position:absolute;right:9px;top:9px;padding:3px 7px;border:1px solid #5b884c;border-radius:12px;color:var(--green);font-size:8px;text-transform:uppercase}.kv{display:grid;grid-template-columns:105px minmax(0,1fr);gap:5px 8px;padding:10px;background:#0d100d;border:1px solid #34372d}.key{color:#777463;text-transform:uppercase;font-size:8px}.value{word-break:break-all;color:#ddd2b4}pre{white-space:pre-wrap;word-break:break-word;background:#090b09;border:1px solid #30342c;padding:9px;color:#d7ddce;font:10px/1.45 ui-monospace,monospace}.record{border-left:2px solid #53604d;padding-left:9px;margin:10px 0}.record.peck{border-color:var(--gold)}.andon{padding:10px;border:1px solid #9d4d3d;background:#351b17;color:#ffc1b5}.empty{color:#777463;padding:15px}
.roster{display:flex;gap:8px;overflow-x:auto;padding:10px}.worker{position:relative;flex:0 0 205px;min-height:66px;border:1px solid #424438;background:#11140f;padding:9px 9px 9px 47px;border-radius:3px}.worker-icon{position:absolute;left:7px;top:12px;width:33px;height:33px}.worker b{color:#e7c675}.health{float:right;text-transform:uppercase;font-size:8px}.health.available{color:var(--green)}.health.degraded{color:var(--gold)}.health.unavailable{color:var(--red)}.small{font-size:9px;color:#7f7b68;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
@media(max-width:1250px){.plant-grid{grid-template-columns:1fr}.inspector{min-height:420px}.inspect-body{max-height:500px}.floor.ten{min-width:940px}}@media(max-width:760px){header{height:auto;flex-wrap:wrap}.brand{height:58px}.header-metrics{display:none}.job{height:58px}.status{height:38px}.plant-grid{display:block}.floor-shell{padding:30px 16px}.floor{grid-template-columns:repeat(2,minmax(150px,1fr))!important;min-width:0!important}.floor.ten .station{grid-row:auto!important;grid-column:auto!important}.floor-shell:before,.floor-shell:after{display:none}.transport{grid-template-columns:auto auto 1fr auto}.transport select,.live-control,.metric{display:none}.inspector{margin-top:10px}}
</style>
</head>
<body>
<header><div class="brand"><span class="brand-mark">🐔</span><h1>BANTAM FACTORY</h1></div><span class="job" id="job"></span><div class="header-metrics"><div class="head-metric"><span>Shift</span><b>NIGHT ◐</b></div><div class="head-metric"><span>Work in process</span><b id="head-wip">—</b></div><div class="head-metric"><span>Traveler</span><b id="head-events">—</b></div></div>${blueprintEndpoint ? `<a class="blueprint-link" href="${escapeHtml(blueprintEndpoint)}">BLUEPRINT</a>` : ""}<span class="status" id="status"></span></header>
<main>
  <div class="plant-grid">
    <section class="plant-deck"><div class="deck-title"><span>Chicken factory floor — click any station</span><span>SUPERVISOR PATROL ACTIVE</span></div><div class="floor-shell"><div class="floor" id="floor"></div></div><div class="transport"><button id="play" title="Play or pause (Space)">▶</button><span id="position"></span><input id="scrubber" type="range" min="1" max="${events.length}" value="${sequence}" title="Traveler position"><button id="latest" title="Jump to latest event (End)">NOW</button><select id="speed" aria-label="Playback speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="2">2×</option><option value="4">4×</option><option value="8">8×</option></select><button id="follow" class="live-control" title="Follow live traveler (L)">${liveEndpoint ? "● LIVE" : "REPLAY"}</button><div class="metric"><b id="clock">—</b><span>factory time</span></div><div class="metric"><b id="elapsed">—</b><span>elapsed</span></div><span id="wip" hidden>—</span><span id="capacity" hidden>—</span></div><div class="timeline-wrap"><div class="timeline" id="timeline"></div></div></section>
    <section class="panel inspector"><h2>Station, chicken & peck inspector</h2><div class="inspect-tabs"><button data-tab="summary" class="active">STANDARD WORK</button><button data-tab="packet">PACKET</button><button data-tab="pecks">PECKS</button><button data-tab="evidence">EVIDENCE</button></div><div class="inspect-body" id="inspector"></div></section>
  </div>
  <section class="panel"><h2>Worker coop — qualification, attendance & capacity</h2><div class="roster" id="roster"></div></section>
</main>
<script id="factory-data" type="application/json">${data}</script>
<script>
'use strict';
const DATA=JSON.parse(document.getElementById('factory-data').textContent);
const CHICKEN_ICON='<svg viewBox="0 0 64 56" aria-hidden="true"><path d="M13 34 3 26l12 1L7 16l17 10" fill="#725934" stroke="#211b13" stroke-width="2"/><path d="M25 43v8m13-8v8m-17 1h9m4 0h9" stroke="#d79031" stroke-width="3" stroke-linecap="round"/><ellipse cx="30" cy="34" rx="20" ry="15" fill="#ead9ae" stroke="#211b13" stroke-width="2.5"/><path d="M18 35q12-13 24 0-9 12-24 0Z" fill="#cba85d" stroke="#766039" stroke-width="2"/><circle cx="45" cy="20" r="10" fill="#f0dfb4" stroke="#211b13" stroke-width="2.5"/><path d="m53 20 9 4-9 4Z" fill="#dd8931" stroke="#211b13" stroke-width="2"/><circle cx="48" cy="18" r="1.8" fill="#111"/><circle cx="39" cy="10" r="4" fill="#c84c3b"/><circle cx="45" cy="8" r="4" fill="#d65a45"/><circle cx="50" cy="11" r="3.5" fill="#c84c3b"/><path d="M45 28q4 7 8 0" fill="#d85c43" stroke="#211b13" stroke-width="1.5"/></svg>';
let EVENTS=DATA.events,EVIDENCE=DATA.evidence||{},WORKFORCE=DATA.workforce;
let selectedAttempt=null,selectedTab='summary',currentSequence=DATA.sequence,playing=false,followLive=Boolean(DATA.liveEndpoint),playTimer=null,liveState=DATA.liveEndpoint?'connecting':'replay';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=v=>esc(JSON.stringify(v,null,2));
const cls=s=>s==='released'?'ok':(['running','awaiting-inspection','awaiting-release','rework'].includes(s)?'wait':(['completed-unverified','answered','observed'].includes(s)?'unknown':'bad'));
const duration=ms=>ms<1000?Math.max(0,ms).toFixed(0)+'ms':ms<60000?(ms/1000).toFixed(1)+'s':ms<3600000?(ms/60000).toFixed(1)+'m':(ms/3600000).toFixed(2)+'h';
function refs(value,out=new Set()){if(typeof value==='string'&&/^sha256:[a-f0-9]{64}$/.test(value))out.add(value);else if(Array.isArray(value))for(const row of value)refs(row,out);else if(value&&typeof value==='object')for(const row of Object.values(value))refs(row,out);return[...out]}
function frame(n){const attempts=new Map(),products=new Map(),andons=[],rework=[];let active=null,released=null,status='running';for(const e of EVENTS.slice(0,n)){const p=e.payload;if(e.type==='job.accepted'){active=released=p.initialProductRevision;products.set(active,{revision:active,parent:null,state:'released'})}else if(e.type==='station.started')attempts.set(p.stationAttempt,{id:p.stationAttempt,ref:p.stationRef,title:p.stationTitle??p.stationAttempt,workerKind:p.workerKind??'legacy',work:p.standardWork??null,state:'running',input:p.inputProductRevision,output:null,gauge:null,telemetry:[],performance:null,startedAt:e.time,lastAt:e.time});else if(e.type==='station.telemetry'){const a=attempts.get(p.stationAttempt);if(a){a.telemetry.push({event:e,value:EVIDENCE[p.artifactRef]});a.lastAt=e.time}}else if(e.type==='station.performance'){const a=attempts.get(p.stationAttempt);if(a){a.performance=p;a.lastAt=e.time}}else if(e.type==='station.completed'){const a=attempts.get(p.stationAttempt);if(a)Object.assign(a,{state:'awaiting-inspection',output:p.outputProductRevision,lastAt:e.time});if(p.outputProductRevision!==p.inputProductRevision)products.set(p.outputProductRevision,{revision:p.outputProductRevision,parent:p.inputProductRevision,state:'awaiting-inspection'});active=p.outputProductRevision}else if(e.type==='station.failed'){const a=attempts.get(p.stationAttempt);if(a)Object.assign(a,{state:p.status,lastAt:e.time})}else if(e.type==='gauge.result'){const a=attempts.get(p.stationAttempt);if(a)Object.assign(a,{gauge:p.status,state:p.status==='pass'?'awaiting-release':p.status,lastAt:e.time});if(p.status!=='pass')status='line-stop'}else if(e.type==='station.released'){const a=attempts.get(p.stationAttempt);if(a)Object.assign(a,{state:'released',lastAt:e.time});const q=products.get(p.productRevision);if(q)q.state='released';active=released=p.productRevision;if(status==='line-stop')status='running'}else if(e.type==='andon.raised'){andons.push({seq:e.seq,...p});status='line-stop'}else if(e.type==='output.contained'){const q=products.get(p.productRevision);if(q){q.state='contained';if(released===p.productRevision)released=q.parent}const a=attempts.get(p.stationAttempt);if(a)a.state='contained';status='line-stop'}else if(e.type==='rework.authorized'){rework.push({seq:e.seq,...p});active=released=p.fromProductRevision;status='rework'}else if(e.type==='job.released'){active=released=p.productRevision;status='released'}else if(e.type==='job.completed'){active=released=p.productRevision;status=p.outcome}else if(e.type==='job.blocked')status='blocked'}return{n,status,active,released,attempts:[...attempts.values()],products:[...products.values()],andons,rework,event:EVENTS[n-1]}}
function stationEvents(id,n=currentSequence){return EVENTS.slice(0,n).filter(e=>e.payload.stationAttempt===id)}
function eventEvidence(events){const found={};for(const event of events)for(const ref of refs(event.payload))if(EVIDENCE[ref]!==undefined)found[ref]=EVIDENCE[ref];return found}
function currentAttention(f){const direct=f.event?.payload?.stationAttempt;if(direct&&f.attempts.some(a=>a.id===direct))return direct;return [...f.attempts].reverse().find(a=>!['released','contained'].includes(a.state))?.id??f.attempts.at(-1)?.id??null}
function activeChassisStation(f){return [...f.attempts].reverse().find(a=>a.output===f.active||a.input===f.active)?.id??null}
function renderFloor(f){const attention=currentAttention(f),cartAt=activeChassisStation(f),target=document.getElementById('floor');if(!selectedAttempt||!f.attempts.some(a=>a.id===selectedAttempt))selectedAttempt=attention;target.className='floor'+(f.attempts.length===10?' ten':'');target.innerHTML=f.attempts.map((a,index)=>{const title=String(a.title).replace(/^S[0-9]+[ ]+/,'');return '<article class="station '+esc(a.state)+(a.id===selectedAttempt?' selected':'')+'" data-attempt="'+esc(a.id)+'"><div class="station-head"><span class="station-index">S'+index+'</span><div><div class="station-title">'+esc(title)+'</div><div class="station-id">'+esc(a.id)+'</div></div></div><div class="machine"><span class="gauge">'+esc(a.gauge??'—')+'</span><span class="button-label">PECK</span><span class="chicken" title="assigned chicken">'+CHICKEN_ICON+'</span></div>'+(a.id===attention?'<span class="rooster" title="supervisor attention">'+CHICKEN_ICON+'</span>':'')+(a.id===cartAt?'<span class="belt-cart" title="active chassis"><span>'+esc(shortRef(f.active))+'</span></span>':'')+'<span class="wicket"></span><div class="station-meta"><span>state</span><b>'+esc(a.state)+'</b><span>worker</span><b>'+esc(a.performance?.workerRef??a.workerKind)+'</b><span>operation</span><b>'+esc(a.work?.operation??'legacy station')+'</b><span>time</span><b>'+esc(a.performance?duration(a.performance.operationMs+(a.performance.inspectionMs??0)):duration(Date.parse(a.lastAt)-Date.parse(a.startedAt)))+'</b><span>pecks</span><b>'+a.telemetry.length+'</b></div></article>'}).join('')||'<div class="empty">The coop is quiet. No station has been dispatched yet.</div>';for(const node of document.querySelectorAll('.station'))node.addEventListener('click',()=>{selectedAttempt=node.dataset.attempt;render(currentSequence)})}
function shortRef(value){const text=String(value??'—');return text.length>17?text.slice(0,8)+'…'+text.slice(-6):text}
function renderTimeline(n){const low=Math.max(0,n-62);document.getElementById('timeline').innerHTML=EVENTS.slice(low,n).map(e=>'<div class="event '+(e.seq===n?'current':'')+'" data-seq="'+e.seq+'" title="#'+e.seq+' · '+esc(e.type)+' · '+esc(e.payload.stationAttempt??e.payload.code??'')+'"><span class="seq">#'+e.seq+'</span><time>'+esc(new Date(e.time).toLocaleTimeString())+'</time><b>'+esc(e.type)+'</b><span class="detail">'+esc(e.payload.stationAttempt??e.payload.code??e.payload.productRevision??'')+'</span></div>').join('');for(const node of document.querySelectorAll('.event'))node.addEventListener('click',()=>{setFollow(false);render(Number(node.dataset.seq))})}
function renderInspector(f){const a=f.attempts.find(row=>row.id===selectedAttempt);const target=document.getElementById('inspector');if(!a){target.innerHTML='<div class="empty">Select a station to inspect its chicken, button, machine, and evidence.</div>';return}const events=stationEvents(a.id),evidence=eventEvidence(events),pecks=a.telemetry.filter(row=>['worker-peck','lifecycle-diagnosis-event','lifecycle-mutation-event','action','observation','turn-start'].includes(row.event.payload.sourceType));if(selectedTab==='summary'){const chassis=a.output??a.input;target.innerHTML='<h3>'+esc(a.title)+'</h3><div class="chassis-preview"><span class="chassis-model"></span><div class="chassis-copy"><b>Chassis at station</b><small>'+esc(shortRef(chassis))+'</small></div><em class="chassis-pass">'+esc(a.gauge??a.state)+'</em></div><div class="kv"><span class="key">attempt</span><span class="value">'+esc(a.id)+'</span><span class="key">station asset</span><span class="value">'+esc(a.ref)+'</span><span class="key">worker</span><span class="value">'+esc(a.performance?.workerRef??a.workerKind)+'</span><span class="key">state / gauge</span><span class="value">'+esc(a.state)+' / '+esc(a.gauge??'—')+'</span><span class="key">input chassis</span><span class="value">'+esc(a.input)+'</span><span class="key">output chassis</span><span class="value">'+esc(a.output??'—')+'</span></div>'+(a.work?'<h3>Standard work</h3>'+list('Operation',[a.work.operation])+list('Instructions',a.work.instructions)+list('Fixtures',a.work.fixtures)+list('Never',a.work.prohibited)+list('Release only when',a.work.releaseCriteria):'<div class="empty">Legacy station: no schema-v2 standard work packet.</div>')+(f.andons.filter(x=>x.detectedAtStation===a.id).map(x=>'<div class="andon"><b>'+esc(x.code)+'</b><br>Chassis '+esc(x.affectedProductRevision)+'</div>').join(''))}else if(selectedTab==='packet'){const packets=Object.entries(evidence).filter(([,v])=>v?.kind==='bantam.factory-work-order'||v?.kind==='bantam.factory-worker-packet');target.innerHTML=packets.length?packets.map(([ref,v])=>record(ref,v,'peck')).join(''):'<div class="empty">No full worker packet was captured for this legacy station.</div>'}else if(selectedTab==='pecks'){target.innerHTML=pecks.length?pecks.map(row=>record('#'+row.event.seq+' '+row.event.payload.sourceType,row.value,'peck')).join(''):'<div class="empty">No model pecks were recorded for this station.</div>'}else{target.innerHTML='<h3>Events</h3>'+events.map(e=>record('#'+e.seq+' '+e.type,e)).join('')+'<h3>Resolved evidence</h3>'+(Object.keys(evidence).length?Object.entries(evidence).map(([ref,v])=>record(ref,v)).join(''):'<div class="empty">No referenced blob evidence.</div>')}}
function list(title,rows){return '<div class="record"><b>'+esc(title)+'</b><ul>'+rows.map(row=>'<li>'+esc(row)+'</li>').join('')+'</ul></div>'}
function record(label,value,kind=''){return '<div class="record '+kind+'"><b>'+esc(label)+'</b><pre>'+pretty(value??{unavailable:true})+'</pre></div>'}
function renderRoster(){const target=document.getElementById('roster');if(!WORKFORCE?.profiles?.length){const crew=[...new Set(frame(EVENTS.length).attempts.map(a=>a.performance?.workerRef??a.workerKind))];target.innerHTML=crew.length?crew.map(worker=>{const roles=frame(EVENTS.length).attempts.filter(a=>(a.performance?.workerRef??a.workerKind)===worker);return '<article class="worker"><span class="worker-icon">'+CHICKEN_ICON+'</span><span class="health available">assigned</span><b>'+esc(shortRef(worker))+'</b><div class="small">traveler-observed line crew</div><div>'+roles.length+' station'+(roles.length===1?'':'s')+'</div><div class="small">'+esc(roles.map(a=>a.title).join(' · '))+'</div></article>'}).join(''):'<div class="empty">No worker has been dispatched yet.</div>';return}target.innerHTML=WORKFORCE.profiles.map(profile=>{const health=WORKFORCE.health.find(row=>row.workerRef===profile.ref&&row.current);const roles=WORKFORCE.qualifications.filter(row=>row.workerRef===profile.ref);return '<article class="worker"><span class="worker-icon">'+CHICKEN_ICON+'</span><span class="health '+esc(health?.condition??'unknown')+'">'+esc(health?.condition??'unknown')+'</span><b>'+esc(profile.id)+'</b><div class="small">'+esc(profile.model)+' · '+esc(profile.reasoningEffort??'default')+'</div><div>roles '+roles.filter(r=>r.status==='qualified').length+' qualified / '+roles.length+' recorded</div><div>slots '+esc(health?.slotsAvailable??'—')+' · quota '+esc(health?.quotaRemaining??'—')+'</div><div class="small">'+esc(profile.ref)+'</div></article>'}).join('')}
function knownCapacity(){if(!WORKFORCE?.health)return'—';const current=WORKFORCE.health.filter(row=>row.current&&row.condition!=='unavailable'&&Number.isFinite(row.slotsAvailable));return current.length?current.reduce((sum,row)=>sum+row.slotsAvailable,0):'—'}
function render(n){n=Math.max(1,Math.min(Number(n),EVENTS.length));currentSequence=n;const f=frame(n),first=EVENTS[0],now=EVENTS[n-1],atLatest=n===EVENTS.length,wip=f.attempts.filter(a=>['running','awaiting-inspection','awaiting-release'].includes(a.state)).length;document.body.classList.toggle('replay',!atLatest);document.getElementById('job').textContent=first.jobId;const status=document.getElementById('status');status.textContent=f.status;status.className='status '+cls(f.status);document.getElementById('position').textContent=n+' / '+EVENTS.length;document.getElementById('head-events').textContent=n+' / '+EVENTS.length;document.getElementById('head-wip').textContent=wip;const scrubber=document.getElementById('scrubber');scrubber.max=EVENTS.length;scrubber.value=n;document.getElementById('clock').textContent=new Date(now.time).toLocaleTimeString();document.getElementById('elapsed').textContent=duration(Date.parse(now.time)-Date.parse(first.time));document.getElementById('wip').textContent=wip;document.getElementById('capacity').textContent=knownCapacity();renderFloor(f);renderTimeline(n);renderInspector(f);updateTransport()}
function updateTransport(){const play=document.getElementById('play'),follow=document.getElementById('follow');play.textContent=playing?'❚❚':'▶';play.classList.toggle('active',playing);follow.className='live-control '+liveState+(followLive?' active':'');follow.textContent=!DATA.liveEndpoint?'REPLAY':liveState==='error'?'● RETRY':followLive?'● LIVE':'○ LIVE';follow.disabled=!DATA.liveEndpoint}
function setFollow(value){followLive=Boolean(DATA.liveEndpoint&&value);if(followLive)render(EVENTS.length);else updateTransport()}
function stopPlayback(){playing=false;if(playTimer){clearTimeout(playTimer);playTimer=null}updateTransport()}
function playbackTick(){if(!playing)return;if(currentSequence>=EVENTS.length){stopPlayback();return}render(currentSequence+1);const speed=Number(document.getElementById('speed').value)||1;playTimer=setTimeout(playbackTick,Math.max(70,650/speed))}
function togglePlayback(){if(playing){stopPlayback();return}setFollow(false);if(currentSequence>=EVENTS.length)render(1);playing=true;updateTransport();playbackTick()}
function samePrefix(next){if(!Array.isArray(next)||next.length<EVENTS.length)return false;for(let i=0;i<EVENTS.length;i++)if(next[i]?.id!==EVENTS[i]?.id)return false;return true}
async function refreshLive(){if(!DATA.liveEndpoint)return;try{const response=await fetch(DATA.liveEndpoint,{cache:'no-store',headers:{accept:'application/json'}});if(!response.ok)throw new Error('snapshot HTTP '+response.status);const snapshot=await response.json();if(snapshot?.kind!=='bantam.factory-floor-snapshot'||snapshot.jobId!==EVENTS[0].jobId||!samePrefix(snapshot.events))throw new Error('snapshot is not an append-only continuation');const wasLatest=currentSequence===EVENTS.length;EVENTS=snapshot.events;EVIDENCE=snapshot.evidence||{};WORKFORCE=snapshot.workforce;liveState='connected';renderRoster();render(followLive||wasLatest?EVENTS.length:currentSequence)}catch(error){liveState='error';const follow=document.getElementById('follow');follow.title='Live refresh failed: '+error.message;updateTransport()}}
document.getElementById('scrubber').addEventListener('input',event=>{setFollow(false);render(Number(event.target.value))});document.getElementById('latest').addEventListener('click',()=>{stopPlayback();setFollow(Boolean(DATA.liveEndpoint));render(EVENTS.length)});document.getElementById('play').addEventListener('click',togglePlayback);document.getElementById('follow').addEventListener('click',()=>setFollow(!followLive));for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>{selectedTab=button.dataset.tab;for(const row of document.querySelectorAll('[data-tab]'))row.classList.toggle('active',row===button);render(currentSequence)});document.addEventListener('keydown',event=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLSelectElement||event.target instanceof HTMLButtonElement)return;if(event.code==='Space'){event.preventDefault();togglePlayback()}else if(event.key==='ArrowLeft'){setFollow(false);render(currentSequence-1)}else if(event.key==='ArrowRight'){setFollow(false);render(currentSequence+1)}else if(event.key==='Home'){setFollow(false);render(1)}else if(event.key==='End'){setFollow(Boolean(DATA.liveEndpoint));render(EVENTS.length)}else if(event.key.toLowerCase()==='l'&&DATA.liveEndpoint)setFollow(!followLive)});renderRoster();render(DATA.sequence);if(DATA.liveEndpoint){refreshLive();setInterval(refreshLive,DATA.pollIntervalMs)}
</script>
</body></html>`;
}

function referencesIn(value, output = new Set()) {
  if (typeof value === "string" && EVIDENCE_REF.test(value)) output.add(value);
  else if (Array.isArray(value)) for (const entry of value) referencesIn(entry, output);
  else if (value && typeof value === "object") for (const entry of Object.values(value)) referencesIn(entry, output);
  return output;
}

function safeScriptJson(value) {
  return JSON.stringify(value)
    .replaceAll("<", "\\u003c")
    .replaceAll(">", "\\u003e")
    .replaceAll("&", "\\u0026")
    .replaceAll("\u2028", "\\u2028")
    .replaceAll("\u2029", "\\u2029");
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[character]);
}
